### ISSUE TITLE
[New Resource] DNS Server Forwarder

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/xDnsServer#19]
Add [DNSServerForwarder](https://technet.microsoft.com/en-us/library/jj649884.aspx) to the list of resources - for configuring forwarders on a DNS Server.

**Comment by corydwood** [comment]
@PlagueHO I've created a pull request to add this resource: #20.

**Comment by PlagueHO** [comment]
Awesome @corydwood ! :+1: I'll go check it out!

**Comment by iainbrighton** [comment]
@KarolKaczmarek Can this be closed as the functionality was merged in #20 ?
