### ISSUE TITLE
xDnsRecord test does not work

### ISSUE THREAD

**Issue by gmatusko** [PowerShell/xDnsServer#23]
I'm using xDnsRecord to create a few A-Records in DNS.  The records are created successfully but when running the script a second time the test returns $false for some reason since the Set script runs and then errors are thrown since the records already exist.  I'll dig into the Test script and see what I can find but wanted to see if others are experiencing this issue.

**Comment by gmatusko** [comment]
OK, I think I figured it out.  I was using xDnsRecord to create round robin DNS entries so the test was returning an array of dns records, not a single record so when the test ran it was doing a -ne $target which won't work on an array.  I changed the test to use -notcontains and that worked for the array of records as well as a single record.

**Comment by iainbrighton** [comment]
This should be a supported scenario though? Are you up to sending a PR with test coverage to ensure this gets fixed and stays fixed? If not, I'll get around to it :)

**Comment by gmatusko** [comment]
Iain,


I won't have time to go through the process so happy to wait.  I'm sure this is a pretty rare case so probably not a show stopper for many.  Thanks.


Greg


________________________________
