### ISSUE TITLE
Resource Module violates PSSA Error rules

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/xDnsServer#26]
The following lines violate the PSSA PSAvoidUsingComputerNameHardcoded rule:
https://github.com/PowerShell/xDnsServer/blob/dev/DSCResources/MSFT_xDnsARecord/MSFT_xDnsARecord.psm1#L68
https://github.com/PowerShell/xDnsServer/blob/dev/DSCResources/MSFT_xDnsARecord/MSFT_xDnsARecord.psm1#L72

The ```-ComputerName "Localhost"``` needs to be removed from these lines.

I will submit a PR.

**Comment by iainbrighton** [comment]
@PlagueHO Whilst that -ComputerName "localhost" is not necessarily required, it's not entirely wrong either (in this instance). Let's get rid of it though - Thanks!

**Comment by PlagueHO** [comment]
@iainbrighton - totally agree- it definitely isn't wrong. But I'll submit the PR.

Related: The iSCSI cmdlets actually operate much faster (4-5 seconds) if you set the -ComputerName parameter to localhost. So setting -computername to Localhost is definitely valid and required in some situations. Cheers!
