### ISSUE TITLE
Tests make changes to build server

### ISSUE THREAD

**Issue by mgreenegit** [PowerShell/xDnsServer#31]
The tests for this module actually load the DNS role on the build server to use the cmdlets, expecting an ephemeral build node.  A better practice would be to mock the DNS cmdlets so the tests can be run on a dev workstation and on perpetual build environments.

**Comment by mgreenegit** [comment]
Tested fix.  Just need to create empty functions for the DNS cmdlets in MSFT_xDnsRecord.Tests.ps1 file.  Will check in fix after further validation.

**Comment by johlju** [comment]
Closing this as resolved. The unit tests seem to mock the cmdlets today. And the integration tests are using the installed DNS server (in AppVeyor).
