### ISSUE TITLE
xDnsServerSetting

### ISSUE THREAD

**Issue by jcwalker** [PowerShell/xDnsServer#36]
If nobody else has started something similar I would like to add a xDnsServerSetting resource to configure the properties of the DNS server.  My plan is to leverage the MicrosoftDNS_Server WMI class to accomplish this.

**Comment by iainbrighton** [comment]
@jcwalker I've not started anything and I'm not aware of anyone with work in progress other than @DrProbie on #34..

**Comment by DrProbie** [comment]
I say go for it…! ☺


Regards/Jonni/DrProbie

**Comment by jcwalker** [comment]
ok Awesome.  I'll get it forked and start on it.

**Comment by jcwalker** [comment]
I'm believe xDnsServerSetting is ready for review.  What are the next steps? Am I to setup an empty branch as documented here: https://github.com/PowerShell/DscResources/blob/master/NewResourceModuleSubmissions.md ?

**Comment by kwirkykat** [comment]
@jcwalker You don't need to make an empty branch. That guide is for submitting a new module (repository). To submit a new resource to this repository you can just open a PR from your fork to the dev branch of this repository.

**Comment by GoateePFE** [comment]
I have done some work along these links. I've attached a ZIP with what I have working. It's been a while since I did this. Listen addresses works well. NetMask ordering had a minor issue. Hopefully this code will help move things along.
[xDNSServerListenAddressesAndNetMaskOrdering.zip](https://github.com/PowerShell/xDnsServer/files/764687/xDNSServerListenAddressesAndNetMaskOrdering.zip)

**Comment by raandree** [comment]
As I need this resource for a project I have taken the code @jcwalker was working on and almost finished the resource and tests.

**Comment by jcwalker** [comment]
@raandree what tests were missing?  I thought I had the unit and integration tests written.  Just waiting for review.

**Comment by raandree** [comment]
Sorry, I was just wondering as the last change on your fork was 7 months ago and pull request is on "wait for author" for more than two months.

I am happy to merge our code. I have taken quite much from your stuff but have added a more flexible and easier maintainable way to compare states.

There was a bug in comparing arrays. The following returns true when using Compare-Array:

``` PowerShell
$a = 1,2,3
$b = 3,2,1

Compare-Array $a $b
```

**Comment by jcwalker** [comment]
Yeah not  sure how the labels work but I'm waiting for a reply from the reviewers.  Not sure if I can change the labels or not.

**Comment by jcwalker** [comment]
@raandree I guess the best way forward for you to contribute is for you to fork my fork and then make a PR to my fork, if that makes sense.
