### ISSUE TITLE
Support for AD-Integrated zones in xDnsServerPrimaryZone

### ISSUE THREAD

**Issue by jcwalker** [PowerShell/xDnsServer#38]
I am working with a customer to leverage DSC to deploy domain controllers and their environment requires a lot of DNS configuration.  They use AD-Integrated zones.  The xDnsServerPrimaryZone resource only supports stand-alone DNS.  Has there been any talk to add the functionality to manage AD-Integrated zones to the xDnsServerPrimaryZone resource?

**Comment by iainbrighton** [comment]
Have you checked out the xDnsServerADZone resource? I think this is the one you're after!

**Comment by jcwalker** [comment]
Awesome.  I didn't noticed the xDnsServerADZone resource.  It is exactly what I need.  Thanks!
