### ISSUE TITLE
Support for Configuring Scavenging

### ISSUE THREAD

**Issue by Persistent13** [PowerShell/xDnsServer#47]
I'd like to add support for scavenging to this module with the introduction of a xDnsServerScavenging resource.

edit: Looking over MSDN for how the WMI classes are implemented I'd also like to create a per-zone scavenging resource called xDnsZoneScavenging.

Is it OK to develop this resource as a class-based one or are script-based resources only accepted in this module?

**Comment by johlju** [comment]
Could this not be added as parameter(s) to the existing *Zone resources? 

Class-based resource are accepted if they can be properly tested and it is possible to add more than one class-based resource, and they can be combined with the existing and new mof-based resources.
There have been attempts by the community to add class-based resource to other modules, like in SqlServerDsc, that attempt was reverted to use mof-based instead. 
See https://github.com/PowerShell/SqlServerDsc/issues/673 and https://github.com/PowerShell/DscResources/issues/331#issuecomment-339633237
