### ISSUE TITLE
xDnsServerPrimaryZone Resource

### ISSUE THREAD

**Issue by iainbrighton** [PowerShell/xDnsServer#5]
We could also do with a DNS Primary Zone resource. The xDnsARecord resource should also work as-is with primary zones..

**Comment by iainbrighton** [comment]
I've started an initial implementation here: https://github.com/iainbrighton/xDnsServer/tree/Issue5

**Comment by PlagueHO** [comment]
I'm very keen on this feature :+1:  I need it to create a GlobalNames zone as well as zones on non-domain joined DNS servers. I'll load your implementation into some of my configs and see how they go. Thanks for starting this one.

**Comment by PlagueHO** [comment]
Is it possible to modify this to create AD Integrated zones? The GlobalNames zone needs to be AD integrated. Plus, I guess it would be useful in general to be able to create AD integrated zones anyway. And while I'm putting my 2c in, it might also be useful to create primary stub zones too :)

**Comment by iainbrighton** [comment]
Due to the differences in the parameter sets of AD Integrated and file-based zones, we will probably need a separate xDnsServerADPrimaryZone resource. Can a GlobalNames zone be standalone or does it have to be AD integrated?

**Comment by PlagueHO** [comment]
GlobalNames can only be AD Integrated so it would only need to be included in the xDNSServerADPrimaryZone. It could possibly be just managed as a boolean parameter in the xDNSServerADPrimaryZone. Also, given that there could never be an xDNSServerADSecondaryZone resource, the name of the resource could just be xDNSServerADZone. I could flesh this out a bit more with some suggested resources and parameter defs in this discussion if that would help?

Also, thinking about this further, integrating a zone into AD would require AD creds to be configured, which would require the WMF 5.0 feature PSDSCRunAsCredentials - and therefore would make an xDNSServerADZone resource only work with WMF5.0, where as the non integrated zones don't require that feature. Same with adding DNS records to integrated zones. So any documentation would need to make this fairly clear.

Thanks! :)

**Comment by corydwood** [comment]
I have an AD integrated resource for this. It uses most of the same code as the xDnsServerPrimaryZone resource, but adds the AD related parameters and removes the ZoneFile parameter. I'll be submitting a Pull Request shortly.

I haven't added support for GlobalNames since I'm not very familiar with them.

**Comment by PlagueHO** [comment]
Nice! Look forward to it :+1:  Once AD integration is supported then automatically GlobalNames zones are now supported.

However, to properly enable a GlobalNames zone also requires the DNS Server be set to use it - by calling:
```powershell
Set-DnsServerGlobalNameZone -Enable:$true
```

But this I think might be best in a new resource. Your thoughts @iainbrighton? Should the GlobalNames zone setting be controlled via a new resource?
