### ISSUE TITLE
DNS Root Hints

### ISSUE THREAD

**Issue by regedit32** [PowerShell/xDnsServer#57]
I'd like to add a resource that manages DNS Server root hints called xDnsServerRootHint.  This can be done using either the MicrosoftDNS_RootHints class or the *-DnsServerRootHint cmdlets.

As far as I can tell, this is not yet covered.  If not, I can start working that.

**Comment by johlju** [comment]
@regedit32 Would be a good addition to the resource.

**Comment by raandree** [comment]
Working on it...
