### ISSUE TITLE
xDnsServerSecondaryZone: Description of masterservers invalid.

### ISSUE THREAD

**Issue by BarnumD** [PowerShell/xDnsServer#65]
Under the readme.md in the xDnsServerSecondaryZone section, it states `MasterServers: IP address or DNS name of the secondary DNS servers`.
However, when I tried a FQDN it failed saying `Cannot convert value "my-server.domain.com" to type "System.Net.IPAddress". Error: "An invalid IP address was specified."`

It would seem that dns names are not allowed despite the documentation saying otherwise?

**Comment by BarnumD** [comment]
I would also like to add that 'masterservers' (plural) make it seem like it should take an array of servers.  But, it seems like this is just a string containing a single ip.

**Comment by johlju** [comment]
The parameter `MasterServers` is an array of strings. Could you test with the latest released version, and provide the verbose output when you get this error?
